name: Code Coverage Report
on:
  push:
    branches:
      - 'master'

jobs:
  coverage-report:
    name: coverage-report
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run Code Coverage & Report
      run: |
        npm install
        npm run test:cov
    - name: Send Report
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
